### ISSUE TITLE
Fingerprint can run flawlessly but it still say "Sorry, fingerprint authentication didn't work. Please try again" & update to 24.11

### ISSUE THREAD

**Issue by Anifyuli** [ahbnr/nixos-06cb-009a-fingerprint-sensor#12]
Hello Mister.
I have some silly problems after setup fingerprint unlock with python-validity. I can use fingerprint on GDM lockscreen, but it always say "Sorry, fingerprint authentication didn't work. Please try again" but it can unlocked. How any idea to fix it? Thanks for read my issue and sorry My English. I wish this project still actived for easily setup in newer version of NixOS.

This is my screenshot to explain my problems.

![Screenshot from 2024-06-27 22-34-47](https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/assets/73734843/e3ab9fe8-e34f-44f1-b8a8-9ded5cca7dc4)

My system info : 
```shell
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.35, NixOS, 24.11 (Vicuna), 24.11.20240624.2893f56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.3`
 - channels(root): `"android-nixpkgs, home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/store/bi5zxc0v5g6ylygdwyqzh280sccg3ykb-source`
```

**Comment by ahbnr** [comment]
Hi!

I'm very sorry for reacting so late to the issues posted here.
I've had some time now to update the flake to work with NixOS 24.11.

Can you try out the following instructions and tell me if it works for you?
https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/blob/b3c609dc2069540cfcfc920d9dc0bd24f530a2bd/SETUP-24.11.md

Please note, that the configuration has changed a lot. 

To make it work with GDM, you will need to first complete the instructions under the section `Setup based on open-fprintd and python-validity`, and then switch to the instructions provided in the section `Setup based on open-fprintd and python-validity`.

**Comment by Anifyuli** [comment]
Sorry Mister, I not using NixOS now and moved to Fedora. So I can't test it now

**Comment by ahbnr** [comment]
No worries, and thank you very much for replying so quickly.
