### ISSUE TITLE
Building repo with flake on unstable fails with patch error

### ISSUE THREAD

**Issue by ericswpark** [ahbnr/nixos-06cb-009a-fingerprint-sensor#15]
Hello! I'm using the following configuration for my T480:
https://github.com/ericswpark/nixos-config/tree/t480-fingerprint

Unfortunately, trying to build with this configuration results in the following build/patch error:

```
error: builder for '/nix/store/5rblak3xirk0cjszsmdiy5jsg98c52zk-fprintd-clients-1.94.3.drv' failed with exit code 1;
       last 16 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/7wfpghw4ykxg3ydx3xm7czwz2is0g28v-source
       > source root is source
       > Running phase: patchPhase
       > applying patch /nix/store/8hx1dpakhd6bd5a5k5ys0ki0bxp6b859-skip-test-test_removal_during_enroll.patch
       > patching file tests/fprintd.py
       > applying patch /nix/store/afphhl36sw5b3kz768qhdinlf8416gl0-Make-building-the-daemon-optional.patch
       > patching file data/meson.build
       > patching file meson.build
       > Hunk #1 succeeded at 89 with fuzz 1.
       > Hunk #2 FAILED at 141.
       > Hunk #3 succeeded at 200 (offset 3 lines).
       > 1 out of 3 hunks FAILED -- saving rejects to file meson.build.rej
       > patching file meson_options.txt
       > patching file src/meson.build
       > patching file tests/meson.build
       For full logs, run 'nix log /nix/store/5rblak3xirk0cjszsmdiy5jsg98c52zk-fprintd-clients-1.94.3.drv'.
error: 1 dependencies of derivation '/nix/store/j5yyj0ijchgm6590bz45byz5zgl54cjk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rb3dz38ykak1han09ialix1fgp5xsl3s-nixos-system-wendy-24.11.20241029.807e915.drv' failed to build
```

**Comment by ericswpark** [comment]
I tried patching the patch file so that it looks for the correct line number for `fprintd` `1.94.3`, but unfortunately the build breaks because it doesn't recognize the `daemon=false` flag.

Seems like more patches are required to get this repo to build for 24.05/unstable :(

https://github.com/ericswpark/nixos-06cb-009a-fingerprint-sensor/commit/133e39b533fbd1df180f8e6d1f53da9da3a5f722

**Comment by ericswpark** [comment]
For now the workaround is to define a NixOS 23.11 input and make this repo follow that instead of unstable/24.05.

**Comment by ahbnr** [comment]
Hi!

I'm very sorry for reacting so late to the issues posted here.
I've had some time now to update the flake to work with NixOS 24.11. This should hopefully also work with NixOS Unstable for now.

Can you try out the following instructions and tell me if it works for you?
https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/blob/b3c609dc2069540cfcfc920d9dc0bd24f530a2bd/SETUP-24.11.md

Please note, that the configuration has changed a lot. 

Unfortunately, I am only using NixOS stable myself, so I will not keep the flake in sync with NixOS unstable.

**Comment by ericswpark** [comment]
Hello, I tried changing over to the new configuration in the new setup README, but I'm getting the following error:

```
       error: attribute 'nixos-06cb-009a-fingerprint-sensor' missing
       at /nix/store/1qkr1s25qyjqng4kw4dm46340bvirwzs-source/flake.nix:35:11:
           34|           # Fingerprint sensor module
           35|           nixos-06cb-009a-fingerprint-sensor.nixosModules."nixos-06cb-009a-fingerprint-sensor"
             |           ^
           36|
```

I am pretty sure the attribute exists:

```
# ...
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable"; # should be the same with stable 24.11
    # ...
    nixos-06cb-009a-fingerprint-sensor = {
      url = "github:ahbnr/nixos-06cb-009a-fingerprint-sensor?ref=24.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

# ...

  outputs = { self,
              nixpkgs,
			  # ...
              nixos-06cb-009a-fingerprint-sensor,
              ...
            }: {
    nixosConfigurations = {
      wendy = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./hosts/wendy/configuration.nix

          # Fingerprint sensor module
          nixos-06cb-009a-fingerprint-sensor.nixosModules."nixos-06cb-009a-fingerprint-sensor"

		  # ...
```

**Comment by ericswpark** [comment]
I figured it out, the attribute name does not have the `nixos-` prefix:

https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/blob/24.11/modules/06cb-009a-fingerprint-sensor/default.nix#L4

The correct module/attribute name is thus the following:

```
outputs = {
  self, nixpkgs,
  # ...
  nixos-06cb-009a-fingerprint-sensor,
  ...
}: {
  nixosConfigurations.<myhostname> = nixpkgs.lib.nixosSystem {
    # ...
    modules = [
      # ...
      nixos-06cb-009a-fingerprint-sensor.nixosModules."06cb-009a-fingerprint-sensor"
    ];
  };
};
```

With this change I can confirm the new configuration builds sucessfully! https://github.com/ericswpark/nixos-config/commit/6ca65752912c0401634d92bf82952a2019c7102a

Thank you for the fix!
