### ISSUE TITLE
Update open-fprintd to 23.11

### ISSUE THREAD

**Issue by mimi0000oo** [ahbnr/nixos-06cb-009a-fingerprint-sensor#7]
Hello,
I tried to install this flake on the latest stable 23.11. It seams as it does not build correctly. I think it is because the flake is ment to be on the 22.11 version

Build error:
`error: builder for '/nix/store/a97j8hcv924la202yn0q55pv86iq5n4y-python3.11-open-fprintd-0.6.drv' failed with exit code 1;
       last 10 log lines:
       >     installer.install(source, destination, {})
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/_core.py", line 109, in install
       >     record = destination.write_file(
       >              ^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 207, in write_file
       >     return self.write_to_fs(scheme, path_, stream, is_executable)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
       >     raise FileExistsError(message)
       > FileExistsError: File already exists: /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/net.reactivated.Fprint.service
       For full logs, run 'nix log /nix/store/a97j8hcv924la202yn0q55pv86iq5n4y-python3.11-open-fprintd-0.6.drv'.`

**Comment by mimi0000oo** [comment]
nix log

`Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/faik5v98hvd8gm8id0kgl4lyvl3l2rla-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/setup.py
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/xkny1w86dwjw4lc8bm4dqn2pfwc9v21n-setup.py.patch
patching file setup.py
applying patch /nix/store/5cf10qxjpzqfgasly2ff23mxypgr6hg4-scripts.patch
patching file scripts/open-fprintd-resume.py (renamed from scripts/resume.py)
patching file scripts/open-fprintd-suspend.py (renamed from scripts/suspend.py)
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/openfprintd
copying openfprintd/__init__.py -> build/lib/openfprintd
copying openfprintd/manager.py -> build/lib/openfprintd
copying openfprintd/device.py -> build/lib/openfprintd
running build_scripts
creating build/scripts-3.11
copying and adjusting dbus_service/open-fprintd -> build/scripts-3.11
copying and adjusting scripts/open-fprintd-suspend.py -> build/scripts-3.11
copying and adjusting scripts/open-fprintd-resume.py -> build/scripts-3.11
changing mode of build/scripts-3.11/open-fprintd from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-suspend.py from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-resume.py from 644 to 755
/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py i>
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
copying and adjusting scripts/open-fprintd-resume.py -> build/scripts-3.11
changing mode of build/scripts-3.11/open-fprintd from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-suspend.py from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-resume.py from 644 to 755
/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py i>
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/__init__.py -> build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/manager.py -> build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/device.py -> build/bdist.linux-x86_64/wheel/openfprintd
running install_data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system-services/
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system.d/
running install_egg_info
running egg_info
creating open_fprintd.egg-info
writing open_fprintd.egg-info/PKG-INFO
writing dependency_links to open_fprintd.egg-info/dependency_links.txt
writing top-level names to open_fprintd.egg-info/top_level.txt
writing manifest file 'open_fprintd.egg-info/SOURCES.txt'
reading manifest file 'open_fprintd.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'open_fprintd.egg-info/SOURCES.txt'
Copying open_fprintd.egg-info to build/bdist.linux-x86_64/wheel/open_fprintd-0.6-py3.11.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd-resume.py -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd-suspend.py -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd-resume.py to 755
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd to 755
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd-suspend.py to 755
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.dist-info/WHEEL
creating 'dist/open_fprintd-0.6-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'open_fprintd-0.6.data/data/share/dbus-1/system-services/net.reactivated.Fprint.service'
adding 'open_fprintd-0.6.data/data/share/dbus-1/system.d/net.reactivated.Fprint.conf'
adding 'open_fprintd-0.6.data/scripts/open-fprintd'
adding 'open_fprintd-0.6.data/scripts/open-fprintd-resume.py'
adding 'open_fprintd-0.6.data/scripts/open-fprintd-suspend.py'
adding 'openfprintd/__init__.py'
adding 'openfprintd/device.py'
adding 'openfprintd/manager.py'
adding 'open_fprintd-0.6.dist-info/COPYING'
adding 'open_fprintd-0.6.dist-info/METADATA'
adding 'open_fprintd-0.6.dist-info/WHEEL'
adding 'open_fprintd-0.6.dist-info/top_level.txt'
adding 'open_fprintd-0.6.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pypaInstallPhase
running install_data
/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py i>
!!
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d/
Traceback (most recent call last):
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d/
Traceback (most recent call last):
        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/net.reactivated.Fprint.service`

**Comment by Gilk260** [comment]
Got the same problem on `NixOs-23.11`

**Comment by mimi0000oo** [comment]
> Got the same problem on `NixOs-23.11`

I updated to 23.11 too. The problem still persists.

**Comment by ahbnr** [comment]
This looks quite similar to what @deviant fixed in their PR: https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/pull/6

Could you test if deviant's change fixes your problem? It should be possible by just setting the flake url to
`"github:deviant/nixos-06cb-009a-fingerprint-sensor/fix-python-validity"`

I unfortunately forgot about the PR (sorry deviant - thank you for your contribution!)
I will be updating to 23.11 myself soon, test the change out, and merge the PR.

**Comment by ahbnr** [comment]
Btw, @mimi0000oo you were originally referring to 23.05, not 23.11.

I'm currently still on 23.05 and it seemed to work fine for me.
Was it a typo by any chance and you were actually referring to 23.11?

**Comment by mimi0000oo** [comment]
> Btw, @mimi0000oo you originally opened this issue for 23.05, not 23.11.
> 
> I'm currently still on 23.05 and it seemed to work fine for me.
> Was it a typo by any chance and you were actually referring to 23.11?

Ya, sorry, I tried to downgrade so as to see what happened and then upgrade again. It is meant to be for 23.11. I will edit it.

**Comment by ahbnr** [comment]
> Edit: If you want any help, I can gladly help you as I have the 06cb:009a sensor on hand!

Have you tried yet if this fix works for you: https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/issues/7#issuecomment-1854544897

**Comment by mimi0000oo** [comment]
> > Edit: If you want any help, I can gladly help you as I have the 06cb:009a sensor on hand!
> 
> Have you tried yet if this fix works for you: [#7 (comment)](https://github.com/ahbnr/nixos-06cb-009a-fingerprint-sensor/issues/7#issuecomment-1854544897) ?

Error from sudo nixos-rebuild switch --flake .
`
error: builder for '/nix/store/a97j8hcv924la202yn0q55pv86iq5n4y-python3.11-open-fprintd-0.6.drv' failed with exit code 1;
       last 10 log lines:
       >     installer.install(source, destination, {})
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/_core.py", line 109, in install
       >     record = destination.write_file(
       >              ^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 207, in write_file
       >     return self.write_to_fs(scheme, path_, stream, is_executable)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
       >     raise FileExistsError(message)
       > FileExistsError: File already exists: /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/net.reactivated.Fprint.service
       For full logs, run 'nix log /nix/store/a97j8hcv924la202yn0q55pv86iq5n4y-python3.11-open-fprintd-0.6.drv'.
error: 1 dependencies of derivation '/nix/store/n98i55qamm6k2lrh03x848f0r8mzkfry-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hbis7pddcy6gxym4aqkdvz2s1rfwkihj-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/snaycjw8vxk066sz1kr9anj50xmay3bf-nixos-system-nixos-23.11.20231207.b4372c4.drv' failed to build`


nix log /nix/store/a97j8hcv924la202yn0q55pv86iq5n4y-python3.11-open-fprintd-0.6.drv:
`
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/faik5v98hvd8gm8id0kgl4lyvl3l2rla-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/setup.py
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/xkny1w86dwjw4lc8bm4dqn2pfwc9v21n-setup.py.patch
patching file setup.py
applying patch /nix/store/5cf10qxjpzqfgasly2ff23mxypgr6hg4-scripts.patch
patching file scripts/open-fprintd-resume.py (renamed from scripts/resume.py)
patching file scripts/open-fprintd-suspend.py (renamed from scripts/suspend.py)
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/openfprintd
copying openfprintd/__init__.py -> build/lib/openfprintd
copying openfprintd/manager.py -> build/lib/openfprintd
copying openfprintd/device.py -> build/lib/openfprintd
running build_scripts
creating build/scripts-3.11
copying and adjusting dbus_service/open-fprintd -> build/scripts-3.11
copying and adjusting scripts/open-fprintd-suspend.py -> build/scripts-3.11
copying and adjusting scripts/open-fprintd-resume.py -> build/scripts-3.11
changing mode of build/scripts-3.11/open-fprintd from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-suspend.py from 644 to 755
changing mode of build/scripts-3.11/open-fprintd-resume.py from 644 to 755
/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/__init__.py -> build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/manager.py -> build/bdist.linux-x86_64/wheel/openfprintd
copying build/lib/openfprintd/device.py -> build/bdist.linux-x86_64/wheel/openfprintd
running install_data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system-services/
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/data/share/dbus-1/system.d/
running install_egg_info
running egg_info
creating open_fprintd.egg-info
writing open_fprintd.egg-info/PKG-INFO
writing dependency_links to open_fprintd.egg-info/dependency_links.txt
writing top-level names to open_fprintd.egg-info/top_level.txt
writing manifest file 'open_fprintd.egg-info/SOURCES.txt'
reading manifest file 'open_fprintd.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'open_fprintd.egg-info/SOURCES.txt'
Copying open_fprintd.egg-info to build/bdist.linux-x86_64/wheel/open_fprintd-0.6-py3.11.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd-resume.py -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
copying build/scripts-3.11/open-fprintd-suspend.py -> build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd-resume.py to 755
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd to 755
changing mode of build/bdist.linux-x86_64/wheel/open_fprintd-0.6.data/scripts/open-fprintd-suspend.py to 755
creating build/bdist.linux-x86_64/wheel/open_fprintd-0.6.dist-info/WHEEL
creating 'dist/open_fprintd-0.6-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'open_fprintd-0.6.data/data/share/dbus-1/system-services/net.reactivated.Fprint.service'
adding 'open_fprintd-0.6.data/data/share/dbus-1/system.d/net.reactivated.Fprint.conf'
adding 'open_fprintd-0.6.data/scripts/open-fprintd'
adding 'open_fprintd-0.6.data/scripts/open-fprintd-resume.py'
adding 'open_fprintd-0.6.data/scripts/open-fprintd-suspend.py'
adding 'openfprintd/__init__.py'
adding 'openfprintd/device.py'
adding 'openfprintd/manager.py'
adding 'open_fprintd-0.6.dist-info/COPYING'
adding 'open_fprintd-0.6.dist-info/METADATA'
adding 'open_fprintd-0.6.dist-info/WHEEL'
adding 'open_fprintd-0.6.dist-info/top_level.txt'
adding 'open_fprintd-0.6.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Finished executing setuptoolsBuildPhase
@nix { "action": "setPhase", "phase": "glibPreInstallPhase" }
glibPreInstallPhase
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pypaInstallPhase
running install_data
/nix/store/y8yq448xka665bqyd5gvdhajqdbsnyys-python3.11-setuptools-68.2.2/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services
copying dbus_service/net.reactivated.Fprint.service -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/
creating /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d
copying dbus_service/net.reactivated.Fprint.conf -> /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system.d/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qjdfq18y24wgsiwlf9f7jnzlsssyil4q-python3.11-installer-0.7.0/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /nix/store/hwix8q7x133ax6achwi8f40fz5a373w5-python3.11-open-fprintd-0.6/share/dbus-1/system-services/net.reactivated.Fprint.service
`

**Comment by mimi0000oo** [comment]
Hey, anything new?

**Comment by ahbnr** [comment]
I created a `release-23.11` branch where I applied deviant's fix commit, as well as another fix.
(That second fix is essentially the same what deviant already did for python-validity, but also applied to the open-fprintd package.)

Could you please test if it works for you? It does seem to work on my system.

Simply use the following URL for the flake:
`github:ahbnr/nixos-06cb-009a-fingerprint-sensor?ref=release-23.11`.

**Comment by mimi0000oo** [comment]
> I created a `release-23.11` branch where I applied deviant's fix commit, as well as another fix. (That second fix is essentially the same what deviant already did for python-validity, but also applied to the open-fprintd package.)
> 
> Could you please test if it works for you? It does seem to work on my system.
> 
> Simply use the following URL for the flake: `github:ahbnr/nixos-06cb-009a-fingerprint-sensor?ref=release-23.11`.

It is indeed working for me too. I was also able to enroll and verify the fingerprint. Thank you!

**Comment by ahbnr** [comment]
Sweet! Thank you for testing.
Also, thanks should mostly go to @deviant who came up with the fix.

I'll merge the `release-23.11` branch into `main` then and close this issue afterwards.
