### ISSUE TITLE
No /lib/security/pam_fprintd.so for authentication

### ISSUE THREAD

**Issue by mimi0000oo** [ahbnr/nixos-06cb-009a-fingerprint-sensor#9]
Hello, I'm back with another issue. First of all I want to thank you for all the support until now!

As I said in the title, I don't have any  **/lib/security/pam_fprintd.so** folder 

For reference, first off all I copied the configuration covered in **README.M**. I soon realized that, the configuration wasn't the problem, but that the **/lib/security/pam_fprintd.so** folder does not exist in the fpritd-clients nix store folder.

### ls /nix/store/279mr18vbq3asrx0qa3x279g9jwxgcbh-fprintd-clients-1.94.2/
`bin  share`

### cat /etc/pam.d/sudo ( it is modified just replaceing that specific line from my personal file )
```
# Account management.
account required pam_unix.so # unix (order 10900)

# Authentication management.
auth sufficient /nix/store/279mr18vbq3asrx0qa3x279g9jwxgcbh-fprintd-clients-1.94.2/lib/security/pam_fprintd.so
auth sufficient pam_unix.so likeauth try_first_pass # unix (order 11600)
auth required pam_deny.so # deny (order 12400)

# Password management.
password sufficient pam_unix.so nullok yescrypt # unix (order 10200)

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0 # env (order 10100)
session required pam_unix.so # unix (order 10200)
```

**Comment by mimi0000oo** [comment]
Hey, any updates on the issue?

**Comment by Dr0med4r** [comment]
Hi I am using this setup and for me the fprintd-clients does also not have a lib folder but i just enabled     `security.pam.services.sudo.fprintAuth = true; `
and my /etc/pam.d/sudo file looks like this:

```
# Account management.
account required pam_unix.so # unix (order 10900)

# Authentication management.
auth sufficient /nix/store/95bpxcma84jnl6a727rc831vydhvpgxd-fprintd-1.94.2/lib/security/pam_fprintd.so # fprintd (order 11300)
auth sufficient pam_unix.so likeauth try_first_pass # unix (order 11500)
auth required pam_deny.so # deny (order 12300)

# Password management.
password sufficient pam_unix.so nullok yescrypt # unix (order 10200)

# Session management.
session required pam_env.so conffile=/etc/pam/environment readenv=0 # env (order 10100)
session required pam_unix.so # unix (order 10200)
```
so the file is in fprintd not fprintd-clients

**Comment by mimi0000oo** [comment]
This fixed it: `security.pam.services.sudo.fprintAuth = true;`

It should be in the docs/readme. Maybe you can do a pull request!
I can also do it if you give me permission! Thank you!

**Comment by Dr0med4r** [comment]
Feel free to do it.
